### ISSUE TITLE
RROR! Unexpected Exception: sequence item 0: expected string, AnsibleMapping found

### ISSUE THREAD

**Issue by ghost** [jonlangemak/ansible_kubernetes#7]
Hi Jon,

I got the following error messages when running ansible-playbook on my Ubuntu-1 master node. 

ben.le@labs-ubuntu-k8-001:~$ ansible-playbook k8s_isntall.yml --ask-become-pass
SUDO password: 
ERROR! Unexpected Exception: sequence item 0: expected string, AnsibleMapping found
to see the full traceback, use -vvv

ben.le@labs-ubuntu-k8-001:~$ ansible-playbook k8s_isntall.yml --ask-become-pass -vvv
Using /etc/ansible/ansible.cfg as config file
SUDO password: 
ERROR! Unexpected Exception: sequence item 0: expected string, AnsibleMapping found
the full traceback was:
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 109, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 154, in run
    results = pbex.run()
  File "/usr/lib/python2.7/dist-packages/ansible/executor/playbook_executor.py", line 81, in run
    pb = Playbook.load(playbook_path, variable_manager=self._variable_manager, loader=self._loader)
  File "/usr/lib/python2.7/dist-packages/ansible/playbook/__init__.py", line 54, in load
    pb._load_playbook_data(file_name=file_name, variable_manager=variable_manager)
  File "/usr/lib/python2.7/dist-packages/ansible/playbook/__init__.py", line 99, in _load_playbook_data
    entry_obj = Play.load(entry, variable_manager=variable_manager, loader=self._loader)
  File "/usr/lib/python2.7/dist-packages/ansible/playbook/play.py", line 115, in load
    data['name'] = ','.join(data['hosts'])
TypeError: sequence item 0: expected string, AnsibleMapping found

Any suggestions?

**Comment by a-curia** [comment]
What version of ubuntu do you use?
Did you do: sudo apt-get install software-properties-common/apt-get install python-software-properties? On Ubuntu 16.04.1 the steps presented in docs does not raise any error(python is already installed). Already test them but i have some problems at the end... etcd not working.
